<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF
8"%> 
<!DOCTYPE html> 
<html lang="en"> 
<head> 
    <meta charset="UTF-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0"> 
    <title>Shopping Cart</title> 
</head> 
<body> 
    <h2>Shopping Cart</h2> 
    <ul> 
        <!-- Shopping cart details will be dynamically generated by the servlet --> 
        <% 
            com.yourpackage.ShoppingCart cart = (com.yourpackage.ShoppingCart) 
session.getAttribute("cart"); 
            if (cart != null) { 
                for (com.yourpackage.Product cartProduct : cart.getProducts()) { 
        %> 
                    <li><%= cartProduct.getName() %> - $<%= cartProduct.getPrice() %></li> 
        <% 
                } 
            } 
        %> 
    </ul> 
    <p>Total: $<%= (cart != null) ? cart.getTotal() : "0.00" %></p> 
    <br><a href='logout'>Logout</a> 
</body> 
</html> 